version: "3.9"

services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo

  client:
    build: ./client
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env
    depends_on:
      - server

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: